# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 03b5274bde186eeed4396ed34f0e0b7a739505efbb6fcbc5df256ca6a871cd91a838c8b3072c6803f89548af995596fa9bcba95845fa6d34b766cd314323e13e

test:
  secret_key_base: 11812bd024e68309d0d3ea94e69b9be1dec1ba26391b5738ff6491c6ab96bf3ca16ed8edd24bf9e162d8ef198123ed073556c75d548d08aa931aefb055e7184f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
